
def draw_man(Attempt):

    print("\n" * 40)


    if Attempt == 1:
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("\n")
        print("    ----------------------------")
    elif Attempt == 2:
        print("\n")
        print("        | ")      
        print("        | ")       
        print("        | ")           
        print("        | ")    
        print("        | ")    
        print("        | ")       
        print("        | ")    
        print("        | ")      
        print("        | ")    
        print("        | ")    
        print("        | ")
        print("    ----------------------------")
    elif Attempt == 3:
        print("        ------------")
        print("        | ")      
        print("        | ")       
        print("        | ")           
        print("        | ")    
        print("        | ")     
        print("        | ")       
        print("        | ")    
        print("        | ")      
        print("        | ")    
        print("        | ")    
        print("        | ")
        print("    ----------------------------")
    elif Attempt == 4:
        print("        ------------")
        print("        | ")      
        print("        | ")       
        print("        | ")           
        print("        | ")    
        print("        | ")     
        print("        | ")       
        print("        | ")    
        print("        | ")      
        print("        | ")    
        print("        |\  ")  
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 5:
        print("        ------------")
        print("        | / ")            
        print("        |/  ")               
        print("        |   ")         
        print("        |   ")  
        print("        |   ")   
        print("        |   ")     
        print("        |   ")  
        print("        |   ")    
        print("        |   ")  
        print("        |\  ")  
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 6:
        print("        ------------")
        print("        | /      | ")       
        print("        |/       | ")                 
        print("        | ")           
        print("        | ")    
        print("        | ")     
        print("        | ")       
        print("        | ")    
        print("        | ")      
        print("        | ")    
        print("        |\   ") 
        print("        | \  ")
        print("    ----------------------------")
    elif Attempt == 7:
        print("        ------------")
        print("        | /      | ")       
        print("        |/       | ")                 
        print("        |      /---\  ")     
        print("        |     |     | ")
        print("        |      \---/  ")  
        print("        | ")       
        print("        | ")    
        print("        | ")      
        print("        | ")    
        print("        |\  ")  
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 8:
        print("       ------------")
        print("        | /      | ")       
        print("        |/       | ")                 
        print("        |      /---\  ")      
        print("        |     | * * | ")
        print("        |      \---/  ")  
        print("        | ")       
        print("        | ")    
        print("        | ")      
        print("        | ")    
        print("        |\   ") 
        print("        | \  ")
        print("    ----------------------------")
    elif Attempt == 9:
        print("        ------------")
        print("        | /      |  ")      
        print("        |/       |  ")                
        print("        |      /---\  ")      
        print("        |     | * * | ")
        print("        |      \---/  ")  
        print("        |        | ")
        print("        |        | ")
        print("        |        | ")     
        print("        |  ")   
        print("        |\  ")  
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 10:
        print("        ------------")
        print("        | /      |  ")      
        print("        |/       |  ")                
        print("        |      /---\  ")      
        print("        |     | * * | ")
        print("        |      \---/  ")  
        print("        |        | ")
        print("        |      ~-| ")
        print("        |        | ")     
        print("        |  ")   
        print("        |\  ")  
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 11:
        print("        ------------")
        print("        | /      |  ")      
        print("        |/       |  ")                
        print("        |      /---\  ")      
        print("        |     | * * | ")
        print("        |      \---/  ")  
        print("        |        | ")
        print("        |      ~-|-~ ")
        print("        |        | ")     
        print("        | ")    
        print("        |\  ")  
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 12:
        print("        ------------")
        print("        | /      |  ")      
        print("        |/       |  ")                
        print("        |      /---\  ")      
        print("        |     | * * | ")
        print("        |      \---/  ")  
        print("        |        | ")
        print("        |      ~-|-~ ")
        print("        |        |  ")    
        print("        |       / ")
        print("        |\     /  ") 
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 13:        
        print("        ------------")
        print("        | /      |  ")      
        print("        |/       |  ")      
        print("        |      /---\ ")       
        print("        |     | * * | ")
        print("        |      \---/ ")
        print("        |        | ")
        print("        |      ~-|-~ ")
        print("        |        | ")
        print("        |       / \ ")
        print("        |\     /   \ ")
        print("        | \ ")
        print("    ----------------------------")
    elif Attempt == 14:
        print("        ------------")
        print("        | /      |   ")     
        print("        |/       |   ")     
        print("        |      /---\  ")      
        print("        |     | X X | ")
        print("        |      \---/ ")
        print("        |      ~-|-~ ")
        print("        |        | ")
        print("        |       / \ ")
        print("        |\     /   \ ")
        print("        | \ ")
        print("    ----------------------------")
